# master 3 nodes
# worker 1 nodes

all:
  hosts:
    master1:
      ansible_host: master1
    master2:
      ansible_host: master2
    master3:
      ansible_host: master3
    worker1:
      ansible_host: worker1
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        worker1:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        calico_rr:
    calico_rr:
      hosts: {}
